routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth'],
], function () {
    Route::resource('users', 'UsersController');
    Route::resource('employee', 'EmployeeController')->except(['create']);
    Route::resource('salon', 'SalonController');
    Route::resource('staff', 'StaffController');
    Route::resource('client', 'ClientController');

    Route::group([
        'namespace' => 'Order'
    ], function () {
        Route::get('/order/calendar', 'OrderListController@calendar')->name('order.list.calendar');
        Route::get('/order/list', 'OrderListController@list')->name('order.list.list');
        Route::get('/order/employees', 'OrderListController@employees')->name('order.list.employees');
        Route::resource('order', 'OrderController');
    });

    Route::group([
        'namespace' => 'Manager'
    ], function () {
        Route::get('/manager/salon', 'SalonController@index')->name('salon.manager.index');
        Route::get('/manager/salon/{salon}/edit', 'SalonController@edit')->name('salon.manager.edit');
        Route::put('/manager/salon/{salon}/update', 'SalonController@update')->name('salon.manager.update');
    });

    Route::group([
        'namespace' => 'Service'
    ], function () {
        Route::delete('/service/user/{service}/{employee}', 'ServiceController@detach')->name('service.detach.user');

        Route::get('/service/{active_category_id?}', 'ServiceController@index')->name('service.index');
        Route::get('/service/create/{category_id}', 'ServiceController@create')->name('service.create');
        Route::post('/service/store', 'ServiceController@store')->name('service.store');
        Route::get('/service/edit/{service}', 'ServiceController@edit')->name('service.edit');
        Route::post('/service/update/{service}', 'ServiceController@update')->name('service.update');
        Route::delete('/service/destroy/{service}', 'ServiceController@destroy')->name('service.destroy');

        Route::post('/service/scope', 'ScopeController@store')->name('service.scope.store');

        Route::post('/service/category/{id}', 'CategoryController@store')->name('service.category.store');
    });

});

Auth::routes();

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Client;
use App\Filter\ClientFilter;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Client\CreateRequest;
use App\Http\Requests\Admin\Client\UpdateRequest;
use App\UseCases\Admin\ClientService;
use Auth;
use Request;

class ClientController extends Controller
{
    /**
     * @var ClientService
     */
    private $clientService;

    public function __construct(ClientService $clientService)
    {
        $this->clientService = $clientService;
    }

    public function index(Request $request)
    {
        $clients = (new ClientFilter())->filter($request, Auth::user()->salon->id);
        return view('admin.client.index', compact('clients'));
    }

    public function create()
    {
        return view('admin.client.create');
    }

    public function store(CreateRequest $request)
    {
        $this->clientService->create($request, Auth::user()->salon);
        return redirect()->route('admin.client.index');
    }

    public function show(Client $client)
    {
        return view('admin.client.show', compact('client'));
    }

    public function edit(Client $client)
    {
        return view('admin.client.edit', compact('client'));
    }


    public function update(UpdateRequest $request, Client $client)
    {
        $this->clientService->update($request, $client);
        return redirect()->route('admin.client.index');
    }

    public function destroy(Client $client)
    {
        $this->clientService->destroy($client);
        return back();
    }
}

resources/views/admin/client/create.blade.php
@extends('layouts.main')
@section('content')
    <form method=POST enctype='multipart/form-data' action="{{ route('admin.client.store') }}">
        @csrf
        <header class="header">
            <div class="back-wrap">
                <a href="{{ route('admin.client.index') }}" class="back-link"></a>
                <h1 class="page-title">Карточка клиента</h1>
            </div>
            <div class="top-buttons">
                <button class="button button--red">Сохранить</button>
            </div>
        </header>
        <main class="main">
            <div class="publish-single">
                <div class="preview-sect">
                    <div class="preview">
                        <div class="image-preview-wrap image-preview-wrap--big image-select">
                            <img src="" alt="" class="image-preview">
                            <div class="new-image"></div>
                            <input type="file" name="photo" class="upload-single-input">
                            <a href="#" class="image-remove"></a>
                        </div>
                        <div class="preview-info-with-titl pl-4">
                            <div class="user-info">
                                <label class="user-info__row feedback-wrap feedback-wrap--auto df">
                                    <span class="bold">Имя:</span> &nbsp;
                                    <input type="text" name="first_name" placeholder="Введите имя" value="{{ old('first_name') }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('first_name') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto df"><span class="bold">Фамилия:</span> &nbsp;
                                    <input type="text" name="last_name" placeholder="Введите фамилию" value="{{ old('last_name') }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('last_name') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto df"><span class="bold">Email:</span> &nbsp;
                                    <input type="email" name="email" placeholder="Введите Email" value="{{ old('email') }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('email') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto df"><span class="bold">Пароль:</span> &nbsp;
                                    <input type="password" name="password" placeholder="**********" value="{{ old('password') }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('password') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto df"><span class="bold">Телефон:</span> &nbsp;
                                    <input type="text" name="phone" placeholder="Введите телефон" value="{{ old('phone') }}" class="input phone">
                                    <span class="invalid-feedback">{{ $errors->first('phone') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto df"><span class="bold">Скидка,%:</span> &nbsp;
                                    <input type="text" name="discount" placeholder="Введите скидку" value="{{ old('discount') }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('discount') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto mb-3"><span class="bold">Статус:</span> &nbsp;
                                    <select name="status" data-placeholder="--" class="select select--no-border w90">
                                        <option></option>
                                        <option value="low" selected>Низкий</option>
                                        <option value="high">Высокий</option>
                                    </select>
                                    <span class="invalid-feedback">{{ $errors->first('status') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto"><span class="bold">Источник:</span> &nbsp;
                                    <select name="source" data-placeholder="--" class="select w150 select--no-border">
                                        <option></option>
                                        <option value="mobile">Мобильное приложение</option>
                                        <option value="admin" selected>Админ. панель</option>
                                    </select>
                                    <span class="invalid-feedback">{{ $errors->first('source') }}</span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </form>
@endsection

resources/views/admin/client/edit.blade.php
@extends('layouts.main')
@section('content')
    <form method=POST enctype='multipart/form-data' action="{{ route('admin.client.update', $client) }}">
        @csrf
        @method('PUT')
        <header class="header">
            <div class="back-wrap">
                <a href="{{ route('admin.client.index') }}" class="back-link"></a>
                <h1 class="page-title">Карточка клиента</h1>
            </div>
            <div class="top-buttons">
                <button class="button button--red">Сохранить</button>
            </div>
        </header>
        <main class="main">
            <div class="publish-single">
                <div class="preview-sect">
                    <div class="preview">
                        <div class="image-preview-wrap image-preview-wrap--big @if(! $client->user->hasImage()) image-select @endif ">
                            <img src="{{ $client->user->getThumb('preview') }}" alt="" class="image-preview">
                            <div class="new-image"></div>
                            <input type="file" name="photo" class="upload-single-input">
                            <a href="#" class="image-remove"></a>
                        </div>
                        <div class="preview-info-with-titl pl-4">
                            <div class="user-info">
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  df">
                                    <span class="bold">Имя:</span> &nbsp;
                                    <input type="text" name="first_name" placeholder="Введите имя" value="{{ old('first_name', $client->user->first_name) }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('first_name') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  df"><span class="bold">Фамилия:</span> &nbsp;
                                    <input type="text" name="last_name" placeholder="Введите фамилию" value="{{ old('last_name', $client->user->last_name) }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('last_name') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  df"><span class="bold">Email:</span> &nbsp;
                                    <input type="email" name="email" placeholder="Введите Email" value="{{ old('email', $client->user->email) }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('email') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  df"><span class="bold">Пароль:</span> &nbsp;
                                    <input type="password" name="password" placeholder="**********" value="{{ old('password', $client->discount) }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('password') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  df"><span class="bold">Телефон:</span> &nbsp;
                                    <input type="text" name="phone" placeholder="Введите телефон" value="{{ old('phone', $client->user->phone) }}" class="input phone">
                                    <span class="invalid-feedback">{{ $errors->first('phone') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  df"><span class="bold">Скидка,%:</span> &nbsp;
                                    <input type="text" name="discount" placeholder="Введите скидку" value="{{ old('discount', $client->discount) }}" class="input">
                                    <span class="invalid-feedback">{{ $errors->first('discount') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto  mb-3 df"><span class="bold">Статус:</span> &nbsp;
                                    <select name="status" data-placeholder="--" class="select select--no-border w90">
                                        <option></option>
                                        <option value="low" selected>Низкий</option>
                                        <option value="high">Высокий</option>
                                    </select>
                                    <span class="invalid-feedback">{{ $errors->first('status') }}</span>
                                </label><br>
                                <label class="user-info__row feedback-wrap feedback-wrap--auto"><span class="bold">Источник:</span> &nbsp;
                                    <select name="source" data-placeholder="--" class="select w150 select--no-border">
                                        <option></option>
                                        <option value="mobile">Мобильное приложение</option>
                                        <option value="admin" selected>Админ. панель</option>
                                    </select>
                                    <span class="invalid-feedback">{{ $errors->first('source') }}</span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </form>
@endsection

resources/views/admin/client/index.blade.php
@extends('layouts.main')
@section('content')
    <header class="header">
        <h1 class="page-title">Клиенты</h1>
        <div class="top-buttons">
            <a href="{{ route('admin.client.create') }}" class="button button--black">Добавить</a>
        </div>
    </header>
    <main class="main">
        <div class="orders-list">
            <form action="/" class="order-top">
                <div class="order-top__inner">
                    <div class="input-row">
                        <div class="date-created">
                            <span class="date-created__title">Дата создания c </span>
                            <label class="input-arrow">
                                <input type="text" placeholder="дд.мм.гггг" class="date-created__input date">
                            </label>
                            по
                            <div class="input-arrow">
                                <input type="text" placeholder="дд.мм.гггг" class="date-created__input date">
                            </div>
                        </div>
                    </div>
                    <div class="input-row">
                        <div class="mr90">
                            <select name="employee" data-placeholder="Выберите сотрудника" class="select w320" id="">
                                <option></option>
                                <option value="1">Иванов Виктор Иванович</option>
                                <option value="2">Сидоров Иван Николаевич</option>
                                <option value="3">Петров Петр Петрович</option>
                            </select>
                        </div>
                        <div class="mr90">
                            <select name="employee" data-placeholder="Выберите пользователя" class="select w320" id="">
                                <option></option>
                                <option value="1">Пользователь 1</option>
                                <option value="2">Пользователь 2</option>
                                <option value="3">Пользователь 3</option>
                            </select>
                        </div>
                        <div>
                            <select name="employee" data-placeholder="Выберите услугу" class="select w320" id="">
                                <option></option>
                                <option value="1">Услуга 1</option>
                                <option value="2">Услуга 2</option>
                                <option value="3">Услуга 3</option>
                                <option value="4">Услуга 4</option>
                            </select>
                        </div>
                    </div>
                    <div class="input-row">
                        <input type="text" placeholder="Введите имя или телефон клиента" class="input">
                    </div>
                    <div class="input-row">
                        <div class="mr50">
                            <select name="employee" data-placeholder="Выберите время визита" class="select w250">
                                <option></option>
                                <option value="1">09:00</option>
                                <option value="2">10:00</option>
                                <option value="2">11:00</option>
                                <option value="2">12:00</option>
                                <option value="2">13:00</option>
                            </select>
                        </div>
                        <div class="mr50">
                            <select name="employee" data-placeholder="Выберите источник" class="select w250">
                                <option></option>
                                <option value="1">Мобильное приложение</option>
                                <option value="1">Веб сайт</option>
                            </select>
                        </div>
                        <div class="mr50">
                            <select name="employee" data-placeholder="Статус клиента" class="select  w250">
                                <option></option>
                                <option value="1">Клиент пришел</option>
                                <option value="1">Клиент не пришел</option>
                            </select>
                        </div>
                        <button class="button button--black mla">Применить</button>
                    </div>
                </div>

            </form>
            @if(! $clients->isEmpty())
                <table class="table">
                    <tr class="table-header">
                        <th class="table-header__item">Имя клиента</th>
                        <th class="table-header__item">Email</th>
                        <th class="table-header__item">Номер телефона</th>
                        <th class="table-header__item">Всего оплачено, руб.</th>
                        <th class="table-header__item">Скидка, %</th>
                        <th class="table-header__item">Статус клиента</th>
                        <th class="table-header__item">Источник</th>
                        <th class="table-header__item table-header__item--control"></th>
                    </tr>
                    @foreach($clients as $client)
                    <tr class="table-body">
                        <td class="table-body__item">{{ $client->user->fullName() }}</td>
                        <td class="table-body__item tac">{{ $client->user->email }}</td>
                        <td class="table-body__item tac">{{ $client->user->phone }}</td>
                        <td class="table-body__item tac">-</td>
                        <td class="table-body__item tac">{{ $client->discount }}</td>
                        <td class="table-body__item tac">
                            {{ App\Entity\Client::getStatus($client->status) }}
                        </td>
                        <td class="table-body__item tac">
                            {{ App\Entity\Client::getSource($client->source) }}
                        </td>
                        <td class="table-body__item table-body__item--control tac">
                            <div class="control-links">
                                <a href="{{ route('admin.client.show', $client) }}" class="control-links__item" style="background-image:url({{ asset('img/edit.svg') }});"></a>
                                <form class="trash-form" action="{{ route('admin.client.destroy', $client) }}" method="POST" >
                                    @csrf
                                    @method('DELETE')
                                    <button class="control-links__item trash-js" data-toggle="modal" data-target="#delete" style="background-image:url( {{ asset('img/trash.svg') }});"></button>
                                    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered maw400" role="document">
                                            <div class="modal-content">
                                                <button type="button" class="map-container__close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <div class="modal-body ">
                                                    <div class="modal-inner tac">
                                                        Вы действительно хотите удалить данную запись?
                                                    </div>
                                                    <div class="modal-trash-control">
                                                        <button class="button button--border-black trash-modal-ok-js">Да</button>
                                                        <button class="button button--black trash-modal-cancel-js">Отмена</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </table>
            @endif
        </div>
    </main>
@endsection

resources/views/admin/client/show.blade.php
@extends('layouts.main')
@section('content')
    <header class="header">
        <div class="back-wrap">
            <a href="{{ route('admin.client.index') }}" class="back-link"></a>
            <h1 class="page-title">Карточка публикации</h1>
        </div>
        <div class="top-buttons">
            <a href="{{ route('admin.client.destroy', $client) }}" class="button button--border-black">Удалить</a>
        </div>
    </header>
    <main class="main">
        <div class="publish-single">
            <div class="preview-sect">
                <div class="preview">
                    <div class="image-preview-wrap image-preview-wrap--big ">
                        <img src="{{ $client->user->getThumb('preview') }}" alt="" class="image-preview">
                    </div>
                    <div class="preview-info-with-title">
                        <div class="user-info">
                            <span class="preview-info__title">{{ $client->user->fullName() }}</span>
                            <div class="user-info">
                                <span class="user-info__row"><span class="bold">Email: </span>{{ $client->user->email }}</span>
                                <span class="user-info__row"><span class="bold">Телефон: </span>{{ $client->user->phone }}</span>
                                <span class="user-info__row"><span class="bold">Скидка,%: </span>{{ $client->user->discount }}</span>
                                <span class="user-info__row"><span class="bold">Статус: </span>{{ App\Entity\Client::getStatus($client->status) }}</span>
                                <span class="user-info__row"><span class="bold">Источник: </span>{{ App\Entity\Client::getSource($client->source) }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="preview-btn-wrap">
                    <a href="{{ route('admin.client.edit', $client) }}" class="button button--red">Редактировать</a>
                </div>
            </div>
        </div>
    </main>
@endsection