routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth'],
], function () {
    Route::resource('users', 'UsersController');
    Route::resource('employee', 'EmployeeController')->except(['create']);
    Route::resource('salon', 'SalonController');
    Route::resource('staff', 'StaffController');
    Route::resource('client', 'ClientController');

    Route::group([
        'namespace' => 'Order'
    ], function () {
        Route::get('/order/calendar', 'OrderListController@calendar')->name('order.list.calendar');
        Route::get('/order/list', 'OrderListController@list')->name('order.list.list');
        Route::get('/order/employees', 'OrderListController@employees')->name('order.list.employees');
        Route::resource('order', 'OrderController');
    });

    Route::group([
        'namespace' => 'Manager'
    ], function () {
        Route::get('/manager/salon', 'SalonController@index')->name('salon.manager.index');
        Route::get('/manager/salon/{salon}/edit', 'SalonController@edit')->name('salon.manager.edit');
        Route::put('/manager/salon/{salon}/update', 'SalonController@update')->name('salon.manager.update');
    });

    Route::group([
        'namespace' => 'Service'
    ], function () {
        Route::delete('/service/user/{service}/{employee}', 'ServiceController@detach')->name('service.detach.user');

        Route::get('/service/{active_category_id?}', 'ServiceController@index')->name('service.index');
        Route::get('/service/create/{category_id}', 'ServiceController@create')->name('service.create');
        Route::post('/service/store', 'ServiceController@store')->name('service.store');
        Route::get('/service/edit/{service}', 'ServiceController@edit')->name('service.edit');
        Route::post('/service/update/{service}', 'ServiceController@update')->name('service.update');
        Route::delete('/service/destroy/{service}', 'ServiceController@destroy')->name('service.destroy');

        Route::post('/service/scope', 'ScopeController@store')->name('service.scope.store');

        Route::post('/service/category/{id}', 'CategoryController@store')->name('service.category.store');
    });

});

Auth::routes();

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Staff;
use App\Filter\StaffFilter;
use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Http\Request;

class StaffController extends Controller
{
    public function index(Request $request)
    {
        $staffs = (new StaffFilter())->filter($request);
        return view('admin.staff.index', compact('staffs'));
    }

    public function create()
    {
        return view('admin.staff.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'description' => 'nullable|string|max:255'
        ]);

        $staff = Staff::make($request->only('name', 'description'));
        $staff->salon()->associate(Auth::user()->salon);
        $staff->save();

        return redirect()->route('admin.staff.index');
    }

    public function edit(Staff $staff)
    {
        return view('admin.staff.edit', compact('staff'));
    }

    public function update(Request $request, Staff $staff)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'description' => 'nullable|string|max:255'
        ]);

        $staff->update($request->only('name', 'description'));
        return redirect()->route('admin.staff.index');
    }

    public function destroy(Staff $staff)
    {
        $staff->delete();
        return redirect()->route('admin.staff.index');
    }
}

resources/views/admin/staff/create.blade.php
@extends('layouts.main')
@section('content')
    <form action="{{ route('admin.staff.store') }}" method="POST" class="scroll-content" enctype="multipart/form-data">
        @csrf
        <header class="header">
            <div class="back-wrap">
                <a href="{{ route('admin.staff.index') }}" class="back-link"></a>
                <h1 class="page-title">Карточка должности</h1>
            </div>
            <div class="top-buttons">
                <button class="button button--red">Сохранить</button>
            </div>
        </header>
        <main class="main">
            <div class="user-single">
                <div class="row">
                    <div class="col-3">
                        <label class="two-spike-input">
                            <span class="two-spike-input__title">Название</span><br>
                            <input type="text" name="name" class="two-spike-input__input input" value="{{ old('name') }}" placeholder="Введите название должности">
                            <span class="invalid-feedback">{{ $errors->first('name') }}</span>
                        </label>
                    </div>
                    <div class="col-3">
                        <label class="two-spike-input">
                            <span class="two-spike-input__title">Описание</span><br>
                            <input type="text" name="description" class="two-spike-input__input input" value="{{ old('description') }}" placeholder="Введите описание должности">
                            <span class="invalid-feedback">{{ $errors->first('description') }}</span>
                        </label>
                    </div>
                </div>
            </div>
        </main>
    </form>
@endsection

resources/views/admin/staff/edit.blade.php
@extends('layouts.main')
@section('content')
    <form action="{{ route('admin.staff.update', $staff) }}" method="POST" class="scroll-content" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <header class="header">
            <div class="back-wrap">
                <a href="{{ route('admin.staff.index') }}" class="back-link"></a>
                <h1 class="page-title">Карточка должности</h1>
            </div>
            <div class="top-buttons">
                <button class="button button--red">Сохранить</button>
            </div>
        </header>
        <main class="main">
            <div class="user-single">
                <div class="row">
                    <div class="col-3">
                        <label class="two-spike-input">
                            <span class="two-spike-input__title">Название</span><br>
                            <input type="text" name="name" class="two-spike-input__input input" value="{{ old('name', $staff->name) }}" placeholder="Введите название должности">
                            <span class="invalid-feedback">{{ $errors->first('name') }}</span>
                        </label>
                    </div>
                    <div class="col-3">
                        <label class="two-spike-input">
                            <span class="two-spike-input__title">Описание</span><br>
                            <input type="text" name="description" class="two-spike-input__input input" value="{{ old('description', $staff->description) }}" placeholder="Введите описание должности">
                            <span class="invalid-feedback">{{ $errors->first('description') }}</span>
                        </label>
                    </div>
                </div>
            </div>
        </main>
    </form>
@endsection

resources/views/admin/staff/index.blade.php
@extends('layouts.main')
@section('content')
    <header class="header">
        <div class="back-wrap">
            <h1 class="page-title">Должности</h1>
        </div>
        <div class="top-buttons">
            <a href="{{ route('admin.staff.create') }}" class="button button--black">Добавить</a>
        </div>
    </header>
    <main class="main">
        <div class="publish-list">
            <div class="top-control">
                <form action="/" class="search-form">
                    <label class="search-form__label">
                        <input type="text" class="search-form__input" placeholder="Введите должность">
                    </label>
                    <button class="search-form__submit">Найти</button>
                </form>
            </div>
            <div class="list">
                <div class="list__content">
                    @foreach($staffs as $staff)
                        <div class="list-item">
                            <div class="list-item__content staff-content">
                                <div>
                                    <span class="list-item__row-text"><span class="bold">Название: </span>{{ $staff->name }}</span>
                                    <span class="list-item__row-text ml100"><span class="bold">Описание: </span>{{ $staff->description }}</span>
                                </div>
                            </div>
                            <div class="list-item__control">
                                <span class="control-links">
                                    <a href="{{ route('admin.staff.edit', $staff) }}" class="control-links__item" style="background-image:url({{ asset('img/edit.svg') }});"></a>
                                    <form class="trash-form" action="{{ route('admin.staff.destroy', $staff) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                            <button class="control-links__item trash-js" data-toggle="modal" data-target="#delete" style="background-image:url( {{ asset('img/trash.svg') }});"></button>
                                            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered maw400" role="document">
                                                    <div class="modal-content">
                                                        <button type="button" class="map-container__close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <div class="modal-body ">
                                                            <div class="modal-inner tac">
                                                                Вы действительно хотите удалить данную запись?
                                                            </div>
                                                            <div class="modal-trash-control">
                                                                <button class="button button--border-black trash-modal-ok-js">Да</button>
                                                                <button class="button button--black trash-modal-cancel-js">Отмена</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                </span>
                            </div>
                        </div>
                    @endforeach
                </div>
                <div class="list__bottom">
                    <nav class="pagination-wrap">
                        {{ $staffs->links() }}
                    </nav>
                </div>
            </div>
        </div>
    </main>
@endsection