routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth'],
], function () {
    Route::resource('users', 'UsersController');
    Route::resource('employee', 'EmployeeController')->except(['create']);
    Route::resource('salon', 'SalonController');
    Route::resource('staff', 'StaffController');
    Route::resource('client', 'ClientController');

    Route::group([
        'namespace' => 'Order'
    ], function () {
        Route::get('/order/calendar', 'OrderListController@calendar')->name('order.list.calendar');
        Route::get('/order/list', 'OrderListController@list')->name('order.list.list');
        Route::get('/order/employees', 'OrderListController@employees')->name('order.list.employees');
        Route::resource('order', 'OrderController');
    });

    Route::group([
        'namespace' => 'Manager'
    ], function () {
        Route::get('/manager/salon', 'SalonController@index')->name('salon.manager.index');
        Route::get('/manager/salon/{salon}/edit', 'SalonController@edit')->name('salon.manager.edit');
        Route::put('/manager/salon/{salon}/update', 'SalonController@update')->name('salon.manager.update');
    });

    Route::group([
        'namespace' => 'Service'
    ], function () {
        Route::delete('/service/user/{service}/{employee}', 'ServiceController@detach')->name('service.detach.user');

        Route::get('/service/{active_category_id?}', 'ServiceController@index')->name('service.index');
        Route::get('/service/create/{category_id}', 'ServiceController@create')->name('service.create');
        Route::post('/service/store', 'ServiceController@store')->name('service.store');
        Route::get('/service/edit/{service}', 'ServiceController@edit')->name('service.edit');
        Route::post('/service/update/{service}', 'ServiceController@update')->name('service.update');
        Route::delete('/service/destroy/{service}', 'ServiceController@destroy')->name('service.destroy');

        Route::post('/service/scope', 'ScopeController@store')->name('service.scope.store');

        Route::post('/service/category/{id}', 'CategoryController@store')->name('service.category.store');
    });

});

Auth::routes();

app/Http/Controllers/Admin/Manager/SalonController.php
<?php

namespace App\Http\Controllers\Admin\Manager;

use App;
use App\Entity\Salon;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Salon\UpdateRequest;
use App\Repositories\ServiceReadRepository;
use App\UseCases\Admin\SalonService;
use Auth;

class SalonController extends Controller
{
    /**
     * @var SalonService
     */
    private $salonService;
    /**
     * @var ServiceReadRepository
     */
    private $serviceReadRepository;

    public function __construct(SalonService $salonService, ServiceReadRepository $serviceReadRepository)
    {
        $this->salonService = $salonService;
        $this->serviceReadRepository = $serviceReadRepository;
    }

    public function index()
    {
        $salon = Auth::user()->salon;
        $services = $this->serviceReadRepository->showServicesWithEmployeeList($salon->id ?? 0);
        return view('admin.salon.manager.index', compact('salon', 'services'));
    }

    public function edit()
    {
        $salon = Auth::user()->salon;
        return view('admin.salon.manager.edit', compact('salon'));
    }

    public function update(UpdateRequest $request, Salon $salon)
    {
        $this->salonService->update($request, $salon);
        return redirect()->route('admin.salon.manager.index');
    }
}

app/Http/Controllers/Admin/SalonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Salon;
use App\Filter\SalonFilter;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Salon\CreateRequest;
use App\Http\Requests\Admin\Salon\UpdateRequest;
use App\Repositories\ServiceReadRepository;
use App\UseCases\Admin\SalonService;
use Illuminate\Http\Request;

class SalonController extends Controller
{
    /**
     * @var SalonService
     */
    private $salonService;
    /**
     * @var ServiceReadRepository
     */
    private $serviceReadRepository;

    public function __construct(SalonService $salonService, ServiceReadRepository $serviceReadRepository)
    {
        $this->salonService = $salonService;
        $this->serviceReadRepository = $serviceReadRepository;
    }

    public function index(Request $request)
    {
        $salons = (new SalonFilter())->filter($request);
        return view('admin.salon.index', compact('salons'));
    }

    public function create()
    {
        return view('admin.salon.create');
    }

    public function store(CreateRequest $request)
    {
        $this->salonService->create($request);
        return redirect()->route('admin.salon.index');
    }

    public function show(Salon $salon)
    {
        $services = $services = $this->serviceReadRepository->showServicesWithEmployeeList($salon->id);
        return view('admin.salon.show', compact('salon', 'services'));
    }

    public function edit(Salon $salon)
    {

        return view('admin.salon.edit', compact('salon'));
    }

    public function update(UpdateRequest $request, Salon $salon)
    {
        $this->salonService->update($request, $salon);
        return redirect()->route('admin.salon.index');
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/SalonController.php
<?php

namespace App\Http\Controllers\Api;

use App\Filter\Api\SalonFilter;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Salon\IndexRequest;
use App\Http\Resources\Salon\SalonResourceCollection;

class SalonController extends Controller
{
    public function index(IndexRequest $request)
    {
        return formattedResponseApi(function () use($request) {
            $filter = new SalonFilter();
            $salons = $filter->filter($request);
            return new SalonResourceCollection($salons);
        });
    }
}

resources/views/admin/salon/create.blade.php
@extends('layouts.main')
@section('content')
<script src="https://api-maps.yandex.ru/2.1/?apikey=1888d523-0c7c-4180-8bb7-7489afc9c71d&lang=ru_RU" type="text/javascript"></script>
<form action="{{ route('admin.salon.store') }}" method="POST" class="scroll-content" enctype="multipart/form-data">
    @csrf
    <header class="header">
        <div class="back-wrap">
            <a href="{{ route('admin.salon.index') }}" class="back-link"></a>
            <h1 class="page-title">Карточка салона</h1>
        </div>
        <div class="top-buttons">
            <button class="button button--red">Cохранить</button>
        </div>
    </header>
    <main class="main">
        <div class="services-single">
            <div class="preview-sect">
                <div class="preview">
                    <div class="image-preview-wrap image-preview-wrap--big image-select">
                        <img src="" alt="" class="image-preview">
                        <div class="new-image"></div>
                        <input type="file" name="photo" class="upload-single-input">
                        <a href="#" class="image-remove"></a>
                    </div>
                    <div class="preview-info-with-title">
                        <span class="preview-info__title w320"><input type="text" class="input" name="title"  value="{{ old('title') }}" placeholder="Название"></span>
                        <table class="preview-info">
                            <tr class="preview-info__row">
                                <td class="preview-info__col pr32">
                                    <input type="text" class="input" name="type"  value="{{ old('type') }}" placeholder="Введите тип объекта">
                                </td>
                                <td class="preview-info__col"><input type="text" name="work_time"  value="{{ old('work_time') }}"  class="input" style="max-width: 200px" placeholder="Введите время работы"></td>
                            </tr>
                            <tr class="preview-info__row">
                                <td class="preview-info__col pr32">
                                    <div class="mt7">
                                        Адрес:
                                        <a href="#" data-toggle="modal" data-target="#mapModal" id="address" class="address">Выберите адрес</a>
                                        <input type="hidden" name="address"  id="address_input"  value="">
                                        <input type="hidden" name="latitude"  value="{{ old('latitude') }}" id="latitude">
                                        <input type="hidden" name="longitude"  value="{{ old('longitude') }}" id="longitude">
                                    </div>
                                </td>
                                <td class="preview-info__col">
                                    <div class="select-constructor">
                                        <div class="select-constructor__control">
                                            <span class="select-constructor__title">Станции метро:</span>
                                            <select name="employee" data-placeholder="Выберите станцию" class="w190 select-constructor__select select select--no-border">
                                                <option></option>
                                                <option value="1" data-type="metro">Автозаводская</option>
                                                <option value="1" data-type="metro">Дубровка</option>
                                                <option value="1" data-type="metro">Кожуховская</option>
                                            </select>
                                            <button class="button button--black select-constructor__control-btn">Добавить</button>
                                        </div>
                                        <div class="select-constructor__content">
                                            <div class="string-constructor-list">

                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="content-sect">
                <div class="content-sect__title-wrap">
                    <span class="content-sect__title">О салоне</span>
                </div>
                <div class="content-sect__inner">
                    <textarea class="textarea" name="description">{{ old('description') }}</textarea>
                </div>
            </div>
            <div class="content-sect">
                <div class="content-sect__title-wrap">
                    <span class="content-sect__title">Реквизиты</span>
                </div>
                <div class="content-sect__inner">
                    <div class="row mb30">
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">Тип</span><br>
                                <input type="text" name="company_type"  value="{{ old('company_type') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">Название юридического лица</span><br>
                                <input type="text" name="company_name"  value="{{ old('company_name') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">Юридический адрес</span><br>
                                <input type="text" name="company_address"  value="{{ old('company_address') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                    </div>
                    <div class="row mb30">
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">ИНН</span><br>
                                <input type="text" name="inn"  value="{{ old('inn') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">КПП</span><br>
                                <input type="text" name="kpp"  value="{{ old('kpp') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">БИК</span><br>
                                <input type="text" name="bik"  value="{{ old('bik') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                    </div>
                    <div class="row mb30">
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">Название банка</span><br>
                                <input type="text" name="bank_name"  value="{{ old('bank_name') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">Кореспондентский счет</span><br>
                                <input type="text" name="correspondent_account"  value="{{ old('correspondent_account') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                        <div class="col-3">
                            <label class="two-spike-input">
                                <span class="two-spike-input__title">Расчетный счет</span><br>
                                <input type="text" name="checking_account"  value="{{ old('checking_account') }}" class="two-spike-input__input input">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-sect">
                <div class="content-sect__title-wrap">
                    <span class="content-sect__title">Сотрудники</span>
                </div>
                <div class="content-sect__inner">
                    <div class="select-constructor" data-name="employee_ids">
                        <div class="select-constructor__control">
                            <select  data-placeholder="Выберите мастера" class="w190 select-constructor__select select select--no-border">
                                <option></option>
                                @foreach(App\Entity\Employee\Employee::getList() as $employee)
                                    <option value="{{ $employee->id }}" data-type="person" data-image="{{ $employee->user->getThumb('preview') }}">{{ $employee->user->fullName() }}</option>
                                @endforeach
                            </select>
                            <button class="button button--black select-constructor__control-btn">Добавить</button>
                        </div>
                        <div class="select-constructor__content">
                            <div class="person-list">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</form>
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered map-container" role="document">
        <div class="modal-content">
            <button type="button" class="map-container__close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="modal-body ">
                <div class="map-container__save"><button id="save-addr" class="button button--red">Сохранить адрес</button></div>
                <div id="map" style="width: 100%; height: 560px"></div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/salon/index.blade.php
@extends('layouts.main')
@section('content')
<header class="header">
    <div class="back-wrap">
        <h1 class="page-title">Салоны</h1>
    </div>
    <div class="top-buttons">
        <a href="{{ route('admin.salon.create') }}" class="button button--black">Добавить</a>
    </div>
</header>
<main class="main">
    <div class="publish-list">
        <form action="/" class="top-control">
            <div class="filter-buttons-list">
                <a href="#" class="filter-button active">Все</a>
                <a href="#" class="filter-button">Новые</a>
                <a href="#" class="filter-button">Ожидают подтверждения</a>
                <a href="#" class="filter-button">Активные</a>
                <a href="#" class="filter-button">Заблокированные</a>
            </div>
        </form>
        <div class="list">
            <div class="list__content">
                <div class="row">
                    @foreach($salons as $salon)
                        <div class="col-6">
                            <a href="{{ route('admin.salon.show', $salon) }}" class="list-item">
                                <div class="list-item__img list-item__img--big">
                                    <img src="{{ $salon->getThumb('grid') }}" class="image" alt="">
                                </div>
                                <div class="list-item__content">
                                    <div class="list-item__row">
                                        <span class="list-item__title">{{ $salon->title }}</span>
                                    </div>
                                    <div class="list-item__row">
                                        <span class="list-item__row-text">{{ $salon->type }}</span>
                                    </div>
                                    <div class="list-item__row">
                                        <span class="rating" data-score="{{ $salon->rating }}"></span>
                                    </div>
                                    <div class="list-item__row">
                                        <span class="list-item__row-text"><span class="bold">Адрес:</span> {{ $salon->address }}</span>
                                    </div>
                                    <div class="list-item__row">
                                        <span class="list-item__row-text"><span class="bold">Время работы: </span>{{ $salon->work_time }}</span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="list__bottom">
                <nav class="pagination-wrap">
                    {{ $salons->links() }}
                </nav>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/salon/show.blade.php
@extends('layouts.main')
@section('content')
<header class="header">
    <div class="back-wrap">
        <a href="{{ route('admin.salon.index') }}" class="back-link"></a>
        <h1 class="page-title">Карточка салона</h1>
    </div>
    <div class="top-buttons">
        <button class="button button--border-black">Заблокировать</button>
    </div>
</header>
<main class="main">
    <div class="services-single">
        <div class="preview-sect">
            <div class="preview">
                <div class="image-preview-wrap image-preview-wrap--big">
                    <img src="{{ $salon->getThumb('preview') }}" alt="" class="image-preview">
                    <div class="new-image"></div>
                </div>
                <div class="preview-info-with-title">
                    <span class="preview-info__title">{{ $salon->title }}</span> <span class="rating ml22" data-score="{{ $salon->rating }}"></span>
                    <table class="preview-info">
                        <tr class="preview-info__row">
                            <td class="preview-info__col pr32">
                                {{ $salon->type }}
                            </td>
                            <td class="preview-info__col">
                                {{ $salon->work_time }}
                            </td>
                        </tr>
                        <tr class="preview-info__row">
                            <td class="preview-info__col pr32">
                                Адрес: {{ $salon->address }}
                            </td>
                            <td class="preview-info__col">Станции метро:
                                <span class="metro-list">
                                            <span class="metro-item">
                                                Автозаводская
                                                <span class="metro-item__mark"  style="background-color: #3BAD39"></span>
                                                <span class="metro-item__mark"  style="background-color: #D71515"></span>
                                            </span>
                                            <span class="metro-item">
                                                Дубровка
                                                <span class="metro-item__mark"  style="background-color: #519ADE"></span>
                                            </span>
                                            <span class="metro-item">
                                                Кожуховская
                                                <span class="metro-item__mark"  style="background-color: #EFA7A7"></span>
                                            </span>
                                        </span>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="preview-btn-wrap">
                <a href="{{ route('admin.salon.edit', $salon) }}" class="button button--red">Редактировать</a>
            </div>
        </div>
        <div class="content-sect">
            <div class="content-sect__title-wrap">
                <span class="content-sect__title">О салоне</span>
            </div>
            <div class="content-sect__inner">
                <p class="text">{{ $salon->description }}</p>
            </div>
        </div>
        @if(! $salon->employees->isEmpty())
            <div class="content-sect">
                <div class="content-sect__title-wrap">
                    <span class="content-sect__title">Сотрудники</span>
                </div>
                <div class="content-sect__inner">
                    <div class="person-list">
                        @foreach($salon->employees as $employee)
                        <div class="person-item">
                            <div class="person-item__img-wrap">
                                <img src="{{ $employee->user->getThumb('preview') }}" alt="" class="image border-round">
                            </div>
                            <span class="person-item__text">{!! str_replace(' ', '<br>', $employee->user->fullName()) !!}</span>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        @endif
        @if(! $services->isEmpty())
            <div class="content-sect">
                <div class="content-sect__title-wrap">
                    <span class="content-sect__title">Позиции</span>
                </div>
                <table class="table">
                    <tr class="table-header">
                        <th class="table-header__item">Название услуги</th>
                        <th class="table-header__item">Сотрудник</th>
                        <th class="table-header__item">Минимальная цена, руб.</th>
                        <th class="table-header__item table-header__item--control"></th>
                    </tr>
                    @foreach($services as $service)
                        <tr class="table-body">
                            <td class="table-body__item tac">{{ $service['service']->name }}</td>
                            <td class="table-body__item tac">{{ $service['employee']->user->fullName() }}</td>
                            <td class="table-body__item tac">{{ $service['service']->price }}</td>
                            <td class="table-body__item table-body__item--control tac">
                                <div class="control-links">
                                    <a href="{{ route('admin.service.edit', $service) }}" class="control-links__item" style="background-image:url({{ asset('img/edit.svg') }});"></a>
                                    <form class="trash-form" action="{{ route('admin.service.detach.user', [$service['service'], $service['employee']]) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                        <button class="control-links__item trash-js" data-toggle="modal" data-target="#delete" style="background-image:url( {{ asset('img/trash.svg') }});"></button>
                                        <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered maw400" role="document">
                                                <div class="modal-content">
                                                    <button type="button" class="map-container__close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <div class="modal-body ">
                                                        <div class="modal-inner tac">
                                                            Вы действительно хотите удалить данную запись?
                                                        </div>
                                                        <div class="modal-trash-control">
                                                            <button class="button button--border-black trash-modal-ok-js">Да</button>
                                                            <button class="button button--black trash-modal-cancel-js">Отмена</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        @endif
    </div>
</main>
@endsection