routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth'],
], function () {
    Route::resource('users', 'UsersController');
    Route::resource('employee', 'EmployeeController')->except(['create']);
    Route::resource('salon', 'SalonController');
    Route::resource('staff', 'StaffController');
    Route::resource('client', 'ClientController');

    Route::group([
        'namespace' => 'Order'
    ], function () {
        Route::get('/order/calendar', 'OrderListController@calendar')->name('order.list.calendar');
        Route::get('/order/list', 'OrderListController@list')->name('order.list.list');
        Route::get('/order/employees', 'OrderListController@employees')->name('order.list.employees');
        Route::resource('order', 'OrderController');
    });

    Route::group([
        'namespace' => 'Manager'
    ], function () {
        Route::get('/manager/salon', 'SalonController@index')->name('salon.manager.index');
        Route::get('/manager/salon/{salon}/edit', 'SalonController@edit')->name('salon.manager.edit');
        Route::put('/manager/salon/{salon}/update', 'SalonController@update')->name('salon.manager.update');
    });

    Route::group([
        'namespace' => 'Service'
    ], function () {
        Route::delete('/service/user/{service}/{employee}', 'ServiceController@detach')->name('service.detach.user');

        Route::get('/service/{active_category_id?}', 'ServiceController@index')->name('service.index');
        Route::get('/service/create/{category_id}', 'ServiceController@create')->name('service.create');
        Route::post('/service/store', 'ServiceController@store')->name('service.store');
        Route::get('/service/edit/{service}', 'ServiceController@edit')->name('service.edit');
        Route::post('/service/update/{service}', 'ServiceController@update')->name('service.update');
        Route::delete('/service/destroy/{service}', 'ServiceController@destroy')->name('service.destroy');

        Route::post('/service/scope', 'ScopeController@store')->name('service.scope.store');

        Route::post('/service/category/{id}', 'CategoryController@store')->name('service.category.store');
    });

});

Auth::routes();

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Проект</title>
    <meta name="viewport" content="width=1500px">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/libs.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
</head>
<body>
<div class="login-container">
    @yield('content')
</div>
<script src="{{ asset('js/libs.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Проект</title>
    <meta name="viewport" content="width=1500px">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/libs.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
</head>
<body>
<div class="wrapper">
    <aside class="sidebar">
        <div class="collapse-menu-btn">
            <span class="collapse-menu-btn__inner"></span>
        </div>
        <nav class="menu-wrap">
            <ul class="menu">
                <!--li class="menu__item active">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/folder.svg') }})"></span>
                        <span class="menu__text">Заказы</span>
                    </a>
                </li>
                <li class="menu__item">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/review.svg') }})"></span>
                        <span class="menu__text">Отзывы</span>
                    </a>
                </li>
                <li class="menu__item">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/persons.svg') }})"></span>
                        <span class="menu__text">Клиенты</span>
                    </a>
                </li>
                <li class="menu__item">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/bell.svg') }})"></span>
                        <span class="menu__text">Публикации</span>
                    </a>
                </li>
                <li class="menu__item">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/house.svg') }})"></span>
                        <span class="menu__text">Профиль салона</span>
                    </a>
                </li>
                <li class="menu__item">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/settings.svg') }})"></span>
                        <span class="menu__text">Управление услугами</span>
                    </a>
                </li-->
                <!--li class="menu__item ">
                    <a href="#" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/bell.svg') }})"></span>
                        <span class="menu__text">Публикации</span>
                    </a>
                </li-->
                <li class="menu__item  {{ Request::routeIs('admin.order*') ? 'active' : '' }}">
                    <a href="{{ route('admin.order.list.calendar') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/folder.svg') }})"></span>
                        <span class="menu__text">Заказы</span>
                    </a>
                </li>
                <li class="menu__item {{ Request::routeIs('admin.client*') ? 'active' : '' }}">
                    <a href="{{ route('admin.client.index') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/persons.svg') }})"></span>
                        <span class="menu__text">Клиенты</span>
                    </a>
                </li>
                <li class="menu__item {{ Request::routeIs('admin.salon.manager*') ? 'active' : '' }}">
                    <a href="{{ route('admin.salon.manager.index') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/house.svg') }})"></span>
                        <span class="menu__text">Профиль салона</span>
                    </a>
                </li>
{{--                <li class="menu__item">--}}
{{--                    <a href="{{ route('admin.salon.index') }}" class="menu__link">--}}
{{--                        <span class="menu__icon" style="background-image: url({{ asset('img/house.svg') }})"></span>--}}
{{--                        <span class="menu__text">Салоны (админ)</span>--}}
{{--                    </a>--}}
{{--                </li>--}}
                <li class="menu__item {{ Request::routeIs('admin.service*') ? 'active' : '' }}">
                    <a href="{{ route('admin.service.index') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/settings.svg') }})"></span>
                        <span class="menu__text">Управление услугами</span>
                    </a>
                </li>
                <li class="menu__item {{ Request::routeIs('admin.employee*') ? 'active' : '' }}">
                    <a href="{{ route('admin.employee.index') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/master.svg') }})"></span>
                        <span class="menu__text">Сотрудники</span>
                    </a>
                </li>
                <li class="menu__item {{ Request::routeIs('admin.staff*') ? 'active' : '' }}">
                    <a href="{{ route('admin.staff.index') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/staff.svg') }})"></span>
                        <span class="menu__text">Должности</span>
                    </a>
                </li>
                <li class="menu__item {{ Request::routeIs('admin.users*') ? 'active' : '' }}">
                    <a href="{{ route('admin.users.index') }}" class="menu__link">
                        <span class="menu__icon" style="background-image: url({{ asset('img/employee.svg') }})"></span>
                        <span class="menu__text">Пользователи</span>
                    </a>
                </li>
            </ul>
        </nav>
    </aside>
    <div class="content">
        @yield('content')
    </div>
</div>
<script src="{{ asset('js/libs.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
</body>
</html>